export const SCORE_UP = "SCORE_UP";
export const SCORE_UP_SUCCESS = "SCORE_UP_SUCCESS";
export const SCORE_UP_ERROR = "SCORE_UP_ERROR";
export const SCORE_DOWN = "SCORE_DOWN";
export const SCORE_DOWN_SUCCESS = "SCORE_DOWN_SUCCESS";
export const SCORE_DOWN_ERROR = "SCORE_DOWN_ERROR";