export const LOAD_TODOS = "LOAD_TODOS"
export const LOAD_TODOS_SUCCESS = "LOAD_TODOS_SUCCESS"
export const LOAD_TODOS_ERROR = "LOAD_TODOS_ERROR"
export const ADD_TODO = "ADD_TODO"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_ERROR = "ADD_TODO_ERROR"
export const DELETE_TODO = "DELETE_TODO"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR"
export const CHECK_TODO = "CHECK_TODO"
export const CHECK_TODO_SUCCESS = "CHECK_TODO_SUCCESS"
export const CHECK_TODO_ERROR = "CHECK_TODO_ERROR"

export const CONTROL_INPUT = "CONTROL_INPUT"

export const SCORE_UP = "SCORE_UP";
export const SCORE_UP_SUCCESS = "SCORE_UP_SUCCESS";
export const SCORE_UP_ERROR = "SCORE_UP_ERROR";
export const SCORE_DOWN = "SCORE_DOWN";
export const SCORE_DOWN_SUCCESS = "SCORE_DOWN_SUCCESS";
export const SCORE_DOWN_ERROR = "SCORE_DOWN_ERROR";

export const LOAD_PLAYER = "LOAD_PLAYER";
export const LOAD_PLAYER_SUCCESS = "LOAD_PLAYER_SUCCESS";
export const LOAD_PLAYER_ERROR = "LOAD_PLAYER_ERROR";
export const ADD_PLAYER = "ADD_PLAYER";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_ERROR = "ADD_PLAYER_ERROR";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_ERROR = "DELETE_PLAYER_ERROR";